# Generated by Django 3.2.20 on 2023-07-27 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity_number', models.BigIntegerField(db_column='商品编号', verbose_name='商品编号')),
                ('three_type', models.CharField(db_column='三级分类', db_index=True, max_length=50, verbose_name='三级分类')),
                ('two_type', models.CharField(db_column='二级分类', max_length=50, verbose_name='二级分类')),
                ('commodity_name', models.TextField(blank=True, db_column='名称', null=True, verbose_name='名称')),
                ('short_name', models.CharField(blank=True, db_column='简称', max_length=255, null=True, verbose_name='简称')),
                ('agent_price', models.DecimalField(db_column='经销价', decimal_places=2, max_digits=10, verbose_name='经销价')),
                ('finance_sales', models.IntegerField(db_column='财务销量', verbose_name='财务销量')),
                ('income', models.DecimalField(db_column='收入', decimal_places=2, max_digits=12, verbose_name='收入')),
                ('unit_price', models.DecimalField(db_column='成交单价', decimal_places=2, max_digits=10, verbose_name='成交单价')),
                ('agent_cost', models.DecimalField(db_column='经销成本', decimal_places=2, max_digits=10, verbose_name='经销成本')),
                ('agent_profit', models.DecimalField(db_column='经销毛利', decimal_places=5, max_digits=6, verbose_name='经销毛利')),
                ('date', models.DateField(db_column='日期', verbose_name='日期')),
            ],
            options={
                'db_table': 'commodity',
            },
        ),
    ]
