# Generated by Django 3.2.20 on 2023-07-29 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_formdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdata',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
