# Generated by Django 3.2.20 on 2023-08-05 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_formdata_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='YieldData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root_lot_id', models.CharField(max_length=10)),
                ('wafer_id', models.CharField(max_length=2)),
                ('yield_value', models.FloatField()),
                ('date', models.DateField()),
            ],
        ),
    ]
