# Generated by Django 3.2.20 on 2023-08-05 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_yielddata'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='yielddata',
            table='yield_table',
        ),
    ]
