# Generated by Django 3.2.20 on 2023-08-05 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_yielddata_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='yielddata',
            table='yield_data',
        ),
    ]
